# Generated by Django 3.2.8 on 2021-10-29 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_images'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Images',
        ),
    ]
