# Generated by Django 3.2.8 on 2021-10-30 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_delete_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(default=None, upload_to='thumbnail-product/%Y/%m'),
        ),
    ]
